### ISSUE TITLE
the big blue gps dot doesn't get redrawn completely

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1087]
![2014-10-23 14 19 42](https://cloud.githubusercontent.com/assets/5685512/4756873/f9ae53c0-5ad0-11e4-9924-3b86a4a5e73d.png)
![2014-10-23 14 19 46](https://cloud.githubusercontent.com/assets/5685512/4756874/face2488-5ad0-11e4-9a8f-454eaca84076.png)

as you can see the big blue gps dot doesn't get redrawn correctly

the issue vanishes if I move around in the map because that enforces a complete redraw

**Comment by cascheberg** [comment]
This (or another bug) also affects drawing of lines that connect MLS lookups.
And sometimes observation points are only drawn when zooming in and out, or even disappear.
I think this is a regression.

**Comment by Djfe** [comment]
Something that should be changed as well:
old points are drawn over new ones
In my Opinion new points should be drawn over old ones instead

**Comment by RexWheeler** [comment]
I find that when I have the map centered (map scrolls with motion) the dots are not drawn as I move. If I zoom in or out, all the dots get redrawn. If I have the map not scroll with motion, the dots get drawn. This is on 0.99 on a Galaxy S4 Active.

**Comment by Djfe** [comment]
That is something I noticed as well. If the GPS is locked then the points don't get drawn or are more spread out, until the GUI gets reloaded (close app completely (only service is open) and then open again)
![2014-10-24 11 49 20](https://cloud.githubusercontent.com/assets/5685512/4810250/f20f2cea-5eb1-11e4-8df3-70bcdd91f000.png)
![2014-10-24 12 07 12](https://cloud.githubusercontent.com/assets/5685512/4810251/f371cb38-5eb1-11e4-8ee3-6905906ec7f9.png)
![2014-10-24 12 07 24](https://cloud.githubusercontent.com/assets/5685512/4810253/f5ea60b4-5eb1-11e4-8812-716dd1dc93e0.png)

and what I also noticed:
sometimes/rarely the GPS icon keeps on glowing after pressing it
![2014-10-24 11 44 34](https://cloud.githubusercontent.com/assets/5685512/4810221/9d79274e-5eb1-11e4-8c6a-2205933347de.png)

maybe this could be used: the icon should keep on glowing if the position is fixed on the GPS position (or it should be switched to a lock icon)

**Comment by garvankeeley** [comment]
Is this still happening?

**Comment by Djfe** [comment]
will test tomorrow

EDIT:
part of the issue: "auto-follow mode should be indicated", is a duplicate of #836

**Comment by Djfe** [comment]
tested using .102
fixed:
&bull the GPS lock related bugs got fixed (points get drawn correctly in follow mode now)
&bull the blue dot get redrawn correctly now

bugs that are still in the app:
&bull the GPS lock/positioning icon, still has the bug that it stays in glowing mode under certain conditions, I was able to find a way to reproduce that 100%:
press GPS positioning icon and swype the drawer open for a few pixels and then push it back in (don't open completely) and the icon stays in glowing mode (needs correct timing, you need to open and close the drawer within the interval in that the icon stays in glowing mode)
EDIT(added a screenshot):
![2014-10-30 10 57 52](https://cloud.githubusercontent.com/assets/5685512/4866982/118b64e0-6131-11e4-900d-15f9b15a98a8.png)

not tested, yet:
&bull are new points drawn over older ones? (happens only on high zoom levels -> dots get closer)

**Comment by Djfe** [comment]
tested now:
&bull are new points drawn over older ones? (happens only on high zoom levels -> dots get closer)
and it happens still:
![2014-10-31 17 12 04](https://cloud.githubusercontent.com/assets/5685512/4866950/9d3b871e-6130-11e4-89c1-c42a4919b464.png)
![2014-10-31 17 12 14](https://cloud.githubusercontent.com/assets/5685512/4866952/9f83b3e8-6130-11e4-97d5-905e23612fa9.png)

**Comment by RexWheeler** [comment]
102 seems to have fixed the drawing of dots when in follow mode for me (per my above comment).

**Comment by cascheberg** [comment]
@Djfe I think this issue should be closed, because the original bug is fixed. And in case of remaining bugs, more specific separate issues should be filed.

**Comment by Djfe** [comment]
well at least the bug this issue was first about isn't fixed 100%
it still happens at higher zoom levels (when you see more) and in lock mode but it fixes itself after some time again

we could close this as it's a cosmetic issue, though

![2015-01-30 17 15 22](https://cloud.githubusercontent.com/assets/5685512/6194504/5f9b02b2-b3c5-11e4-8dd8-2ee62f8c005b.png)
![2015-02-01 18 32 12](https://cloud.githubusercontent.com/assets/5685512/6194509/64063204-b3c5-11e4-92e0-b462e986287c.png)

**Comment by cascheberg** [comment]
@Djfe The blue GPS dot itself is drawn correctly in your screeshots, isn't it?
The only minor issue that I see that is left is

> old points are drawn over new ones

**Comment by Djfe** [comment]
yeah

> old points are drawn over new ones

that and the blue gps dot gets drawn correctly but other points are drawn on top of it

**Comment by cascheberg** [comment]
The remaining problem of old points being drawn over new ones is probably because of 8ea0f5febcda0519ef88c6c514d848148798f75f. @garvankeeley Is it ok to change that? It is probably nicer to have newest points drawn on top, although they will be drawn last then.

@Djfe I think dots should be drawn on top of the blue dot as is, so that they remain visible even around the current location. Also the situation should occur less often once #1371 is fixed.

**Comment by lua86** [comment]
Can't the new one be drawn "again" last?

**Comment by Djfe** [comment]
What do you mean? This patches it so that new points will be drawn last instead of first so that old points will end up below new ones

**Comment by cascheberg** [comment]
The problem is that new points are drawn first, so as a result older points end up being drawn on top. But the good reason for drawing newer points first is that drawing is stopped after a certain time if the device is too slow (see #1545). And it makes sense to leave out older points instead of newer ones.
@lua86 all points are always redrawn, only putting the latest one on top is not much of an improvement
@Djfe I suggest you close this issue now. There is no fix in sight, the remaining problem is a minor cosmetic one, and the whole issue has become quite unreadable.

**Comment by Djfe** [comment]
Ok I understand now what lua86 meant

One last chance:
What about using png tiles instead of redrawing the dots everytime
Since their position doesn't change it would make sense I guess, since it should improve performance on low end devices as well and dots can always be drawn on top.
The only dot that needs to be redrawn is the GPS dot

I'm wondering though how this could affect zooming performance and how much space it costs.
Probably not too much space since tiles are only changed where you are going to

**Comment by garvankeeley** [comment]
Our preferred approach would be to draw directly to the raster tiles on disk. The only reason it is drawn as an on-screen overlay is for simplicity. Same thing for the coverage tiles. Those should be permanently overlaid on the map tiles. We are planning to start drawing more objects (like cell towers) on the map, this would also benefit from being drawn to the on-disk tiles.

**Comment by garvankeeley** [comment]
BTW, drawing to a separate PNG raster for the observation points would be a performance killer. Raster compositing on the fly is the biggest chunk of our existing rendering problems, and we are only doing 2 of them (map + coverage). A third would be a disaster. The correct approach is to draw to 1 raster, and have that render. In that case, the current location will still be drawn on top of observation points.

**Comment by garvankeeley** [comment]
The discussion was useful, but I am going to close this bug, as I don't see anything actionable here, although I don't object to new bugs being created for specific issues that were raised during this discussion if they are still happening.

**Comment by Djfe** [comment]
ok good arguments you brought up there
and it's good that this issue got closed now since the most important bugs in this discussion now got fixed anyway :)
