### ISSUE TITLE
Extend map lookup to send cell data

### ISSUE THREAD

**Issue by hannosch** [mozilla/MozStumbler#141]
The MapActivity / "locate me" code only sends wifi data to the server. But the server also supports and has cell data for lookups (for about a month now).

Would be good to extend the code to also send the cell data along.

**Comment by Djfe** [comment]
@garvankeeley doesn't MozStumbler already send cell data along with search requests?
if so then you can close this issue ;)

**Comment by garvankeeley** [comment]
The MLS locate is currently unhooked, we are showing GPS-only mp locations in the latest builds, but I would like that we add MLS location also, users can see the MLS error for the location they are in, they can see the MLS improve over time when resembling, and maybe even help us detect areas with broken MLS location.

**Comment by Djfe** [comment]
well yeah, but this has been fixed already before MLS got unhooked, right?
and it will get implemented again by #733

**Comment by garvankeeley** [comment]
I'll have to check, I didn't fix it, and if fixed, the fixer didn't mark the issue fixed :)

**Comment by Djfe** [comment]
![I see what you did there](http://store.donanimhaber.com/35/e7/c2/35E7C24EF113A560AB7FCD132AB0B2E0.jpg)

little Tongue-twister :D

**Comment by Djfe** [comment]
fixed now, I think
(you can enable MLS lookups in the settings)

**Comment by garvankeeley** [comment]
Yup, we send everything to MLS for location
