### ISSUE TITLE
"Already Sent" metrics deleted with each application start

### ISSUE THREAD

**Issue by hbogner** [mozilla/MozStumbler#1536]
Mozilla Stumbler version 1.7.2 from F-Droid
Android 4.4.4 Cyanogen OS version 11.0-XNPH05Q

Metrics go back to zero on each application start.
Cleared cache, data, and reinstalled the app, and no help.

![2015-03-04 16 05 48](https://cloud.githubusercontent.com/assets/794472/6491451/8a9b82f6-c2ad-11e4-8807-a9059adfd52a.png)
![2015-03-04 16 18 30](https://cloud.githubusercontent.com/assets/794472/6491455/8c392d66-c2ad-11e4-9711-91bb8963418f.png)

**Comment by garvankeeley** [comment]
Can you check in 1.7.4? I think this is fixed.

**Comment by hbogner** [comment]
Only 1.7.3 on F-Droid. Will wait for 1.7.4. and then test.

**Comment by Djfe** [comment]
The issue is that the metrics only update when the first upload happens
This has been fixed

**Comment by hbogner** [comment]
No it's not fixed.
I upgraded to 1.7.3. and I had some reports few minutes ago, and now my metrics is back to 0.
Already sent is wiped clean.
Older version on other phone 1.5.2 still counts sent reports, but 1.7.2 and 1.7.3 delete number of sent reports.

**Comment by Djfe** [comment]
Yeah because the fix is in 1.7.4

**Comment by hbogner** [comment]
OK. THX, will test it out tomorrow.

**Comment by cascheberg** [comment]
The bug still exists in 1.7.4. Sometimes the numbers are updated on start, sometimes they are not. I did not yet try to investigate any further when this fails.

**Comment by crankycoder** [comment]
This is probably a bug I introduced to @garvankeeley's patch that pushes an intent for statistics. I added a zeroe'd stats metric if nothign can be read from disk.  That should probably be changed to a subclass that means "NullStatEvent" instead of a zeroed metric.

**Comment by hbogner** [comment]
As @cascheberg said, still present in 1.7.4. No matter how many reports are sent, it always goes back to 0(zero) on next aplication start.
@crankycoder I hope you know how to fix it :D

**Comment by crankycoder** [comment]
Patch is being tested tonight.  This one was all my fault. Sorry!

**Comment by hbogner** [comment]
Using 1.7.7 from F-Droid.
Still get for "Already sent" section in metrics:
"Last upload: never"
"Reports: "
Tried clearing cache and data, and reinstalling the app.
Nothing helped.

**Comment by crankycoder** [comment]
If you clear the cache and data, those metrics should go to zero - there is no more data to read from storage.

Can you screenshot your application with specific steps to reproduce?

I just tested with the build from F-Droid. Version 1.7.7 71 ddf1a-dirty and the "already sent" metrics show up properly for me.

With stumbler on, the "ready to send" increment up correctly:

![2015-03-17 10 37 54](https://cloud.githubusercontent.com/assets/4829/6689730/79189214-cc92-11e4-8285-211333d5e686.png)

Toggling the switch off to force an upload causes "ready to send" to flush back down to 0 and the last upload times get updated correctly:

![2015-03-17 10 40 37](https://cloud.githubusercontent.com/assets/4829/6689750/98b97570-cc92-11e4-8b21-c400e3402556.png)

After a force kill and restart:

![2015-03-17 10 41 04](https://cloud.githubusercontent.com/assets/4829/6689709/563a23b6-cc92-11e4-9b4b-74cb851183b3.png)

**Comment by hbogner** [comment]
I know that the option to clear the cache and data wipes all data from the app.
What I meant to explain is that I cleared cache and data, then collected some reports and sent them and got "never" after the next start. Then tried removing the app and reinstalling it again, collected some reports and sent them and got "never" again.

But in 1.7.7 now I see some changes, which I missed in last message.
When starting the app after rebooting the phone there are
"Last upload: one day ago" and "Reports: 40 (36.8KB)"
So this means you fixed the clear to zero on every start.

But after some testing the pattern of what happens became clear.
Clear start of app lists correct "Already sent" metrics.
After stopping the scan, exiting the app(pressing back or home button), and starting it again with the new scan it shows  "Last upload: never".
But when killing the app and making the clear start again it shows correct "Already sent" metrics again.

So stopping the scan reports the metrics as empty but keeps the correct values in the background, and they are updated correctly with next clear start of the app.

Hope this helps.

**Comment by hbogner** [comment]
Forgot the screenshots in the last post
This is after clean start today:
![2015-03-17 18 05 47](https://cloud.githubusercontent.com/assets/794472/6698003/f5554d42-ccf4-11e4-8537-327dff01ac7f.png)
This is after exiting the app and starting again today:
![2015-03-17 18 07 54](https://cloud.githubusercontent.com/assets/794472/6698005/f871b196-ccf4-11e4-8ef0-f6d9458a94d9.png)
This is again after clean start just now:
![2015-03-17 21 31 36](https://cloud.githubusercontent.com/assets/794472/6698070/bf2e03e8-ccf5-11e4-8bd0-4cd179970f10.png)
This is after exiting the app and starting again just now:
![2015-03-17 21 37 32](https://cloud.githubusercontent.com/assets/794472/6698146/6fbe687e-ccf6-11e4-92e3-6cf77009651d.png)

**Comment by hbogner** [comment]
1.7.10 and 1.7.11 still report empty metrics on app start.
After the first upload it shows correct numbers.

![2015-04-03 10 10 58](https://cloud.githubusercontent.com/assets/794472/7033084/df81acb6-dd77-11e4-8d21-099a136ec86d.png)
![2015-04-03 10 21 27](https://cloud.githubusercontent.com/assets/794472/7033086/e141db2a-dd77-11e4-977b-f78dd57050de.png)
![2015-04-07 13 48 25](https://cloud.githubusercontent.com/assets/794472/7033088/e2f37bf4-dd77-11e4-8208-16d3ecb67930.png)
![2015-04-07 13 49 02](https://cloud.githubusercontent.com/assets/794472/7033089/e519c3ac-dd77-11e4-9992-b3edb8134996.png)

**Comment by crankycoder** [comment]
Strange.  When I do a force kill and restart, I get metrics on my build:

![2015-04-07 16 50 19](https://cloud.githubusercontent.com/assets/4829/7033225/9e27e48c-dd46-11e4-9e96-0d9fd99ae8f5.png)

This is using a dev build after the 1.7.12 release mind you.

**Comment by cascheberg** [comment]
I can confirm that this is still happening sometimes, I'd say rarely. I wished I had steps to reproduce.

**Comment by crankycoder** [comment]
This is probably a race condition between registration to listen to intents broadcast by the `PersistedStats` class.

Currently - the ClientStorageManager makes a request to the `PersistedStats` class to broadcast the metrics from storage. There's no guarantee that this happens _after_ `MetricsView` constructor has completed.  

One solution is to modify `MetricsView` so that it records the first time `PersistedStats.ACTION_PERSISTENT_SYNC_STATUS_UPDATED` is received.   When `MetricsView::onOpened` is invoked, we can check if no sync stats were ever received and force the update to occur.
