### ISSUE TITLE
Link to MLS home page and privacy policy

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#883]
MozStumbler should probably link to the MLS home page and privacy policy:

https://location.services.mozilla.com

https://location.services.mozilla.com/privacy

**Comment by Djfe** [comment]
The link to MLS is already there in the about page.

**Comment by garvankeeley** [comment]
The first run dialog links to the privacy policy:
https://github.com/mozilla/MozStumbler/pull/897

**Comment by Djfe** [comment]
@crankycoder fixed by now

**Comment by crankycoder** [comment]
We have a link to the main https://location.services.mozilla.com/ page in the about, but we are still missing the privacy link.

I'm leaving this open until we add the privacy link to the about activity as it's perfectly reasonable for people to want to see the privacy policy after the first run.
